###
# COMPOSE CONFIGURATION FILE
###

services:
  postgres:
    image: postgres:17.4
    container_name: postgres
    environment:
      POSTGRES_DB: todo-list
      POSTGRES_PASSWORD: todosecret
      POSTGRES_USER: todouser
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_HTTP_PORT: 8081
    ports:
      - 8081:8081
    volumes:
      - ./src/main/resources/keycloak/config:/opt/keycloak/data/import
